version: '3.9'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:20
    working_dir: /usr/src/fit-home-api
    restart: always
    command: bash -c "npm install --omit=dev && npm install nodemon -D && npm run debug"
    environment:
      - MONGO_URL
    volumes:
      - ./dist/:/usr/src/fit-home-api/dist/
      - ./package.json:/usr/src/fit-home-api/package.json/
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
